/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoquesystem;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author borgeImages/
 */
public class StartScreen2 extends javax.swing.JFrame {
 DefaultTableModel df = null;
    ButtonGroup tg = new ButtonGroup();
    DBOperations db = new DBOperations();
    /**
     * Creates new form StartScreen2
     */
    public StartScreen2() throws IOException {
        initComponents();
        Icon icon = new ImageIcon (getClass().getResource ("iconfinder.png" ));
        lblstatus.setIcon(icon);
        
         int i=0;
        List list =new ArrayList();
        tg.add(rdnome);
        tg.add(rdforne);
        tg.add(rdmarca);
        list = db.populateComboBoxTipo();
          
        while (i < list.size()) {
            cmbtipo.addItem(list.get(i).toString());
            i++;
        }
       
        populateTable(db.populateTableEstoque("Mouse"));
        //layer.moveToFront(teste);
    }
        
       
    
    
    private void populateTable(List list) {
        String[] column = {"Nome", "Marca", "Quantidade", "Fornecedor"};
        List<Produto> prod = list;//CONSULTA
        String[] p = new String[6];
        String[][] m = null;

        df = new DefaultTableModel(m, column);
        //POPULANDO TABELA
        for (int i = 0; i < prod.size(); i++) {
            p[0] = prod.get(i).getNome();
            p[1] = prod.get(i).getMarca();
            p[2] = String.valueOf(prod.get(i).getQuantidade());
            p[3] = prod.get(i).getFornecedor();

            df.addRow(p);

        }
        tableEstoque.setModel(df);
        teste.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btngeren = new javax.swing.JButton();
        btnforne = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        btngeren2 = new javax.swing.JButton();
        btngeren3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        layer = new javax.swing.JLayeredPane();
        consualta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEstoque = new javax.swing.JTable();
        txtpesq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        rdmarca = new javax.swing.JRadioButton();
        rdforne = new javax.swing.JRadioButton();
        rdnome = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cmbtipo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        teste = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtpesq1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnbuscar1 = new javax.swing.JButton();
        rdmarca1 = new javax.swing.JRadioButton();
        rdforne1 = new javax.swing.JRadioButton();
        rdnome1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(19, 43, 72));
        jPanel1.setForeground(new java.awt.Color(19, 43, 72));

        btngeren.setBackground(new java.awt.Color(19, 43, 72));
        btngeren.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngeren.setForeground(new java.awt.Color(255, 255, 255));
        btngeren.setText("Gerenciar Produtos");
        btngeren.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btngeren.setBorderPainted(false);
        btngeren.setOpaque(false);
        btngeren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btngerenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btngerenMouseExited(evt);
            }
        });
        btngeren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngerenActionPerformed(evt);
            }
        });

        btnforne.setBackground(new java.awt.Color(19, 43, 72));
        btnforne.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnforne.setForeground(new java.awt.Color(255, 255, 255));
        btnforne.setText("Fornecedores");
        btnforne.setBorder(null);
        btnforne.setBorderPainted(false);
        btnforne.setOpaque(false);
        btnforne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnforneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnforneMouseExited(evt);
            }
        });
        btnforne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        lblstatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(255, 255, 255));
        lblstatus.setText("Administrador");

        btngeren2.setBackground(new java.awt.Color(19, 43, 72));
        btngeren2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngeren2.setForeground(new java.awt.Color(255, 255, 255));
        btngeren2.setText("Compras");
        btngeren2.setBorder(null);
        btngeren2.setBorderPainted(false);
        btngeren2.setOpaque(false);
        btngeren2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btngeren2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btngeren2MouseExited(evt);
            }
        });
        btngeren2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeren2ActionPerformed(evt);
            }
        });

        btngeren3.setBackground(new java.awt.Color(19, 43, 72));
        btngeren3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btngeren3.setForeground(new java.awt.Color(255, 255, 255));
        btngeren3.setText("Clientes");
        btngeren3.setBorder(null);
        btngeren3.setBorderPainted(false);
        btngeren3.setOpaque(false);
        btngeren3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btngeren3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btngeren3MouseExited(evt);
            }
        });
        btngeren3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeren3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EstoqueSystem");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyright");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Version: beta 1.0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btngeren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnforne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btngeren2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btngeren3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblstatus))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstatus)
                .addGap(18, 18, 18)
                .addComponent(btngeren, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnforne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngeren2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngeren3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        consualta.setBackground(new java.awt.Color(255, 255, 255));

        tableEstoque.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tableEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Marca", "Quantidade", "Fornecedor"
            }
        ));
        jScrollPane2.setViewportView(tableEstoque);

        txtpesq.setBackground(new java.awt.Color(204, 204, 204));
        txtpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Pesquisar");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        rdmarca.setText("marca");

        rdforne.setText("fornecedor");

        rdnome.setText("nome");
        rdnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnomeActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_delete.png"))); // NOI18N
        jButton2.setText("Excluir Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(19, 97, 115));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_add.png"))); // NOI18N
        jButton1.setText("Novo Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(19, 97, 115));
        jButton9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/information.png"))); // NOI18N
        jButton9.setText("Info");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        cmbtipo.setBackground(new java.awt.Color(102, 102, 102));
        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "produto" }));
        cmbtipo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                cmbtipoPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbtipoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbtipo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                cmbtipoComponentHidden(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel8.setText("Gerenciador de produtos");

        javax.swing.GroupLayout consualtaLayout = new javax.swing.GroupLayout(consualta);
        consualta.setLayout(consualtaLayout);
        consualtaLayout.setHorizontalGroup(
            consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consualtaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consualtaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consualtaLayout.createSequentialGroup()
                                .addComponent(rdnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdforne, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(consualtaLayout.createSequentialGroup()
                                .addComponent(txtpesq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar)))
                        .addGap(228, 228, 228))
                    .addGroup(consualtaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(consualtaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18))))
        );
        consualtaLayout.setVerticalGroup(
            consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consualtaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consualtaLayout.createSequentialGroup()
                        .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consualtaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnome)
                    .addComponent(rdforne)
                    .addComponent(rdmarca))
                .addGap(14, 14, 14))
        );

        teste.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CNPJ", "Endereço"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton11.setBackground(new java.awt.Color(19, 97, 115));
        jButton11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/information.png"))); // NOI18N
        jButton11.setText("Info");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(19, 97, 115));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_add.png"))); // NOI18N
        jButton3.setText("Novo Fornecedo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_delete.png"))); // NOI18N
        jButton5.setText("Excluir Fornecedor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel7.setText("Fornecedores");

        txtpesq1.setBackground(new java.awt.Color(204, 204, 204));
        txtpesq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesq1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Pesquisar");

        btnbuscar1.setText("Buscar");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        rdmarca1.setText("Endereço");

        rdforne1.setText("CNPJ");

        rdnome1.setText("nome");
        rdnome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testeLayout = new javax.swing.GroupLayout(teste);
        teste.setLayout(testeLayout);
        testeLayout.setHorizontalGroup(
            testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testeLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(testeLayout.createSequentialGroup()
                        .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(testeLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(testeLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(testeLayout.createSequentialGroup()
                                        .addComponent(rdnome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdforne1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdmarca1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(testeLayout.createSequentialGroup()
                                        .addComponent(txtpesq1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnbuscar1)))))
                        .addGap(194, 194, 194))))
        );
        testeLayout.setVerticalGroup(
            testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testeLayout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesq1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(testeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnome1)
                    .addComponent(rdforne1)
                    .addComponent(rdmarca1))
                .addContainerGap())
        );

        layer.setLayer(consualta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layer.setLayer(teste, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layerLayout = new javax.swing.GroupLayout(layer);
        layer.setLayout(layerLayout);
        layerLayout.setHorizontalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consualta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layerLayout.setVerticalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consualta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(teste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layer))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layer)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngerenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngerenMouseEntered
        // TODO add your handling code here:
        btngeren.setBackground(Color.GREEN);
    }//GEN-LAST:event_btngerenMouseEntered

    private void btngerenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngerenMouseExited
        // TODO add your handling code here:
         btngeren.setBackground(Color.getColor("132B48"));
    }//GEN-LAST:event_btngerenMouseExited

    private void btnforneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnforneMouseEntered
        // TODO add your handling code here:
        btnforne.setBackground(Color.green);
    }//GEN-LAST:event_btnforneMouseEntered

    private void btnforneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnforneMouseExited
        // TODO add your handling code here:
        btnforne.setBackground(Color.getColor("132B48"));
    }//GEN-LAST:event_btnforneMouseExited

    private void btngeren2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngeren2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeren2MouseEntered

    private void btngeren2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngeren2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeren2MouseExited

    private void btngeren2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeren2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeren2ActionPerformed

    private void btnforneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforneActionPerformed
        // TODO add your handling code here:
        layer.moveToFront(teste);
        teste.setVisible(true);
        consualta.setVisible(false);
    }//GEN-LAST:event_btnforneActionPerformed

    private void btngeren3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngeren3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeren3MouseEntered

    private void btngeren3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngeren3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeren3MouseExited

    private void btngeren3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeren3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeren3ActionPerformed

    private void txtpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesqActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String filtro = "nome";
        if (rdnome.isSelected()) {
            filtro = "nome";
        } else if (rdforne.isSelected()) {
            filtro = "fornecedor";
        } else if (rdmarca.isSelected()) {
            filtro = "marca";
        }
        df.getDataVector().removeAllElements();
        populateTable(db.procurar(filtro, txtpesq.getText()));
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void rdnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row= tableEstoque.getSelectedRow();

        String nome= tableEstoque.getValueAt(row, 0).toString();

        int opc=JOptionPane.showConfirmDialog(this,"Tem certeza que deseja deletar este produto ?");

        if(opc==JOptionPane.YES_OPTION){
            for(int i=0;i<db.produtoList.size();i++){

                if(nome.equals(db.produtoList.get(i).getNome())){
                    db.deleteProduto(db.produtoList.get(i).getId());
                    df.getDataVector().remove(row);
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NewProdutScreen p = new NewProdutScreen();
        p.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        InfoScreen im = new InfoScreen();
        int row= tableEstoque.getSelectedRow();
        String nome= tableEstoque.getValueAt(row, 0).toString();
        for(int i=0;i<db.produtoList.size();i++){

            if(nome.equals(db.produtoList.get(i).getNome()) ){

                im.setFields(db.produtoList.get(i).getNome(),db.produtoList.get(i).getMarca(),db.produtoList.get(i).getFornecedor(),db.produtoList.get(i).getPreco(),db.produtoList.get(i).getQuant(),db.produtoList.get(i).getDesc());
                im.show();
            }
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void cmbtipoPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbtipoPopupMenuCanceled
        // TODO add your handling code here:
        df.getDataVector().removeAllElements();
        populateTable(db.populateTableEstoque(cmbtipo.getSelectedItem().toString()));
    }//GEN-LAST:event_cmbtipoPopupMenuCanceled

    private void cmbtipoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbtipoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        df.getDataVector().removeAllElements();
        populateTable(db.populateTableEstoque(cmbtipo.getSelectedItem().toString()));
    }//GEN-LAST:event_cmbtipoPopupMenuWillBecomeInvisible

    private void cmbtipoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbtipoComponentHidden
        // TODO add your handling code here:
        df.getDataVector().removeAllElements();
        populateTable(db.populateTableEstoque(cmbtipo.getSelectedItem().toString()));
    }//GEN-LAST:event_cmbtipoComponentHidden

    private void btngerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngerenActionPerformed
        // TODO add your handling code here:
        layer.moveToFront(consualta);
        consualta.setVisible(true);
        teste.setVisible(false);
    }//GEN-LAST:event_btngerenActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtpesq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesq1ActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void rdnome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StartScreen2().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StartScreen2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btnforne;
    private javax.swing.JButton btngeren;
    private javax.swing.JButton btngeren2;
    private javax.swing.JButton btngeren3;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JPanel consualta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JRadioButton rdforne;
    private javax.swing.JRadioButton rdforne1;
    private javax.swing.JRadioButton rdmarca;
    private javax.swing.JRadioButton rdmarca1;
    private javax.swing.JRadioButton rdnome;
    private javax.swing.JRadioButton rdnome1;
    private javax.swing.JTable tableEstoque;
    private javax.swing.JPanel teste;
    private javax.swing.JTextField txtpesq;
    private javax.swing.JTextField txtpesq1;
    // End of variables declaration//GEN-END:variables
}
